"""Reads the two subset fonts and writes what the rest of the build needs.

Run from `scripts/subset-fonts.sh` inside a fontTools environment; it is not a
standalone tool.

Two outputs:

1. `src/assets/fonts/coverage.json` — every character the subsets can draw.
   `scripts/check-font-coverage.mjs` compares the built pages against this file,
   which is why it can be plain Node with no font parser and no `uv`: CI reads
   the committed list instead of opening a woff2.

2. The `size-adjust` / `ascent-override` / `descent-override` numbers for the
   fallback `@font-face` rules in `global.css`, printed for a human to paste in.
   They are not generated into the stylesheet: `global.css` is hand-written and
   the metrics only move when the fonts themselves are replaced.
"""

import json
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

OUT, ROOT = sys.argv[1], sys.argv[2]

# The weight each family is actually rendered at, so the width comparison below
# is made at the size the reader sees: headings are 560, body text is 400.
SUBSETS = [
    ("bricolage-grotesque-subset.woff2", 600),
    ("golos-text-subset.woff2", 400),
]

# Fallback faces, in the order `global.css` names them. macOS and Windows ship
# the same Monotype files, so the metrics are the same on both; a machine
# without them simply falls through to the next family in the stack.
FALLBACKS = [
    ("bricolage-grotesque-subset.woff2", "Arial", ["/System/Library/Fonts/Supplemental/Arial.ttf",
                                         "/Library/Fonts/Arial.ttf",
                                         "C:/Windows/Fonts/arial.ttf"]),
    ("golos-text-subset.woff2", "Arial", ["/System/Library/Fonts/Supplemental/Arial.ttf",
                                             "/Library/Fonts/Arial.ttf",
                                             "C:/Windows/Fonts/arial.ttf"]),
]

# Enough of the alphabet to compare two fonts' running width. A plain mean over
# these is steadier than OS/2's xAvgCharWidth, which several foundries fill in
# by different rules.
SAMPLE = "abcdefghijklmnopqrstuvwxyz "


def avg_width(font):
    """Mean advance of SAMPLE, as a fraction of the em."""
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    widths = [hmtx[cmap[ord(c)]][0] for c in SAMPLE if ord(c) in cmap]
    return (sum(widths) / len(widths)) / font["head"].unitsPerEm


def vertical(font):
    """Ascent, descent and line gap as fractions of the em.

    Browsers read OS/2's typographic metrics when USE_TYPO_METRICS is set and
    hhea otherwise, so the overrides have to follow the same rule.
    """
    upem = font["head"].unitsPerEm
    os2 = font["OS/2"]
    if os2.fsSelection & (1 << 7):
        asc, desc, gap = os2.sTypoAscender, os2.sTypoDescender, os2.sTypoLineGap
    else:
        hhea = font["hhea"]
        asc, desc, gap = hhea.ascender, hhea.descender, hhea.lineGap
    return asc / upem, abs(desc) / upem, gap / upem


coverage = {}
metrics = {}
for name, weight in SUBSETS:
    path = os.path.join(OUT, name)
    font = TTFont(path)
    coverage[name] = sorted(font.getBestCmap())
    axes = {a.axisTag: a for a in font["fvar"].axes}
    print(
        f"{name}: {len(coverage[name])} characters, "
        f"axes {', '.join(f'{t} {a.minValue:g}–{a.maxValue:g}' for t, a in axes.items())}"
    )
    at = {"wght": max(axes["wght"].minValue, min(weight, axes["wght"].maxValue))}
    metrics[name] = instancer.instantiateVariableFont(TTFont(path), at, inplace=False)

with open(os.path.join(OUT, "coverage.json"), "w", encoding="utf-8") as fh:
    json.dump(
        {
            "note": "Generated by scripts/subset-fonts.sh. Code points each subset font can draw.",
            "fonts": coverage,
        },
        fh,
        indent=2,
    )
    fh.write("\n")
print(f"wrote {os.path.relpath(os.path.join(OUT, 'coverage.json'), ROOT)}")

print("\nfallback @font-face metrics (paste into src/styles/global.css):")
for name, fallback, candidates in FALLBACKS:
    path = next((p for p in candidates if os.path.exists(p)), None)
    if path is None:
        print(f"  {fallback}: not installed here — numbers left unchanged")
        continue
    real = metrics[name]
    fb = TTFont(path)
    size_adjust = avg_width(real) / avg_width(fb)
    asc, desc, gap = vertical(real)
    print(f"  /* {name} over local(\"{fallback}\") */")
    print(f"  size-adjust: {size_adjust * 100:.2f}%;")
    print(f"  ascent-override: {asc / size_adjust * 100:.2f}%;")
    print(f"  descent-override: {desc / size_adjust * 100:.2f}%;")
    print(f"  line-gap-override: {gap / size_adjust * 100:.2f}%;")
